import type { Metadata } from 'next'
import { Providers } from './providers'
import Profile from './components/Profile'
import Tabs from './components/Tabs'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html suppressHydrationWarning>
      <body className={inter.className}>
        <div className="w-full max-w-[600px] p-6 m-auto">
          <Providers>
            <Profile />
            <Tabs className="my-6" />
            {children}
          </Providers>
        </div>
      </body>
    </html>
  )
}
